controllers:
    resource: ../../src/Controller/
    type: annotation

rock:
    resource: '@RockBundle/Controller/'
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
